# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class MulDivStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Mul = channel.unary_unary(
        '/endpoints.MulDiv/Mul',
        request_serializer=service__pb2.Numbers.SerializeToString,
        response_deserializer=service__pb2.Result.FromString,
        )
    self.Div = channel.unary_unary(
        '/endpoints.MulDiv/Div',
        request_serializer=service__pb2.Numbers.SerializeToString,
        response_deserializer=service__pb2.Result.FromString,
        )


class MulDivServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Mul(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Div(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MulDivServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Mul': grpc.unary_unary_rpc_method_handler(
          servicer.Mul,
          request_deserializer=service__pb2.Numbers.FromString,
          response_serializer=service__pb2.Result.SerializeToString,
      ),
      'Div': grpc.unary_unary_rpc_method_handler(
          servicer.Div,
          request_deserializer=service__pb2.Numbers.FromString,
          response_serializer=service__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'endpoints.MulDiv', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
