# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='endpoints',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rservice.proto\x12\tendpoints\"\x1f\n\x07Numbers\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\"\x19\n\x06Result\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2h\n\x06MulDiv\x12.\n\x03Mul\x12\x12.endpoints.Numbers\x1a\x11.endpoints.Result\"\x00\x12.\n\x03\x44iv\x12\x12.endpoints.Numbers\x1a\x11.endpoints.Result\"\x00\x62\x06proto3'
)




_NUMBERS = _descriptor.Descriptor(
  name='Numbers',
  full_name='endpoints.Numbers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='endpoints.Numbers.a', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='endpoints.Numbers.b', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=59,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='endpoints.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='endpoints.Result.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['Numbers'] = _NUMBERS
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Numbers = _reflection.GeneratedProtocolMessageType('Numbers', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERS,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.Numbers)
  })
_sym_db.RegisterMessage(Numbers)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:endpoints.Result)
  })
_sym_db.RegisterMessage(Result)



_MULDIV = _descriptor.ServiceDescriptor(
  name='MulDiv',
  full_name='endpoints.MulDiv',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=88,
  serialized_end=192,
  methods=[
  _descriptor.MethodDescriptor(
    name='Mul',
    full_name='endpoints.MulDiv.Mul',
    index=0,
    containing_service=None,
    input_type=_NUMBERS,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Div',
    full_name='endpoints.MulDiv.Div',
    index=1,
    containing_service=None,
    input_type=_NUMBERS,
    output_type=_RESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MULDIV)

DESCRIPTOR.services_by_name['MulDiv'] = _MULDIV

# @@protoc_insertion_point(module_scope)
